### ISSUE TITLE
Player crashes during scanning song Collection 

### ISSUE THREAD

**Issue by SanaShporlyuk** [gyunaev/spivak#9] opened 2018-01-25 00:08 UTC
_# Priority/Severity: High/Critical_
_Environment: Ubuntu 16.04, 64 bit
Karaoke version 1.3_

The crash occurs when user updates song Collection. Looks like file's timestamps are parsed in wrong way.
STR:
1. Run player =>File menu =>Preferences... => Collection Tab
2. Add existed root directory of collection
3. Click Update button
4. In dialog box "Update the collection" click "Yes"

Actual result:
Player crashes

Expected result:
Player scans user's files

LOG
..../files/spivak.2/spivak/build$ src/spivak
DEBUG Background objects: 5 loaded
DEBUG Background objects: 5 loaded
DEBUG Music collection: 8 music files found
Protocol error: bad 3 (Window); Sequence Number 5
 Opcode (20, 0) = GetProperty
 Bad resource 1414682966 (0x54525956)
 at -e line 15.
DEBUG PluginManager: attempting to load plugin plugin_langdetect from /usr/lib64/spivak/plugins/plugin_langdetect.so
ERROR PluginManager: failed to load plugin plugin_langdetect from /usr/lib64/spivak/plugins/plugin_langdetect.so: The shared library was not found.
DEBUG SongDatabaseScanner: cleanup thread started
DEBUG SongDatabaseScanner: cleanup thread finished
DEBUG SongDatabaseScanner: submitting thread started
DEBUG SongDatabaseScanner: procesing thread started
DEBUG SongDatabaseScanner: procesing thread started
DEBUG SongDatabaseScanner: scanCollectionsThread started
DEBUG SongDatabaseScanner: collection thread will ignore the timestamps earlier than 2018-13-24 15:13:52
ERROR SongDatabaseScanner: Invalid line in the collection index: 
ERROR SongDatabaseScanner: Invalid line in the collection index: 
DEBUG SongDatabaseScanner: scanCollectionsThread finished
DEBUG SongDatabaseScanner: procesing thread finished
DEBUG SongDatabaseScanner: last procesing thread finished, signaling the submitter to shut down
DEBUG SongDatabaseScanner: submitter thread finished, scan completed
DEBUG SongDatabaseScanner: submitting thread started
DEBUG SongDatabaseScanner: procesing thread started
DEBUG SongDatabaseScanner: procesing thread started
DEBUG SongDatabaseScanner: cleanup thread started
DEBUG SongDatabaseScanner: cleanup thread finished
DEBUG SongDatabaseScanner: scanCollectionsThread started
DEBUG SongDatabaseScanner: collection thread will ignore the timestamps earlier than 2018-15-24 15:15:57
Segmentation fault (core dumped)

******************************** 
misspelling in debugger
procesing -> processing
********************************

![scan](https://user-images.githubusercontent.com/23021102/35363636-c92636c0-011f-11e8-8919-ea2a425a5c92.png)

![update](https://user-images.githubusercontent.com/23021102/35363645-d30ce274-011f-11e8-81ba-5e6a2f2f98c4.gif)

**Comment by gyunaev** [comment] 2018-03-30 23:44
Can't reproduce the crash. Can you please attach gdb backtrace?

The invalid date shown is fixed in adf2b34..bbf21d4

**Closed** 2020-01-04 07:48 UTC
Labels: bug, more info needed
